gems:
    - jekyll-redirect-from
# Site settings
title: Allegro Open Source
menu: false
# email: kariera@allegro.pl
description: "We use Open Source solutions on daily basis here at Allegro Group, why not work on our karma and give something in return? Welcome at our open source technology blog."
name: Allegro Tech Blog
baseurl: ""
url: "http://allegrotech.io"
twitter_username: AllegroTechBlog
github_username:  allegro

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

kramdown:
    input: GFM
    coderay_line_numbers: nil
permalink: /:title.html

