# Site settings
title: Allegro Open Source
menu: false
# email: kariera@allegro.pl
description: ""
baseurl: ""
url: "http://allegro.github.io"
twitter_username: AllegroTechBlog
github_username:  allegro

# Build settings
markdown: redcarpet
kramdown:
    input: GFM
    coderay_line_numbers: nil
permalink: /:title.html

