# Site settings
title: Allegro | open source
email: kariera@allegro.pl
description: ""
baseurl: ""
url: "http://allegro.github.io"
twitter_username: AllegroTechBlog
github_username:  allegro

# Build settings
markdown: kramdown
permalink: pretty
