gems:
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-paginate-v2

# Site settings
title: allegro.tech
menu: false
#email: kariera@allegro.pl
description: "We use Open Source solutions on a daily basis here at Allegro Group. Why not work on our karma and give something in return? Welcome to our open source technology blog."
name: allegro.tech blog
baseurl: ""
url: "http://allegro.tech"
twitter_username: AllegroTechBlog
github_username:  allegro
facebook_username: allegro.tech
google_plus_id: +AllegroTechBlog
meetup_username: allegrotech
slideshare_username: allegrotech

kramdown:
    input: GFM
    hard_wrap: false
    coderay_line_numbers: nil

sass:
    sass_dir: css/partials

permalink: /:year/:month/:title.html

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 10

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

 # Optional,omit or set both before and after to zero to disable.
 # Controls how the pagination trail for the paginated pages look like.
 # We set it to 100 on each side, because we need the full pagination in order to build our Metrum pagination
  trail:
    before: 100
    after: 100

############################################################
